### ISSUE TITLE
firestore の セキュリティエラー時の画面表示方法修正

### ISSUE THREAD

**Issue by haterain0203** [haterain0203/limited_characters_diary#197]
## やること
- 現状だと、アプリ全体が操作不可になるため、問い合わせもできない
- firestore に関係がない「設定」画面は表示できるようにすべき

## 備考
-

**Comment by haterain0203** [comment]
debug * prod で実行したところ、以下エラーが起きていることを確認した

```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following FirebaseException was thrown building UnderRepairDialog(dirty, dependencies:
[UncontrolledProviderScope], state: _ConsumerState#f7556):
[cloud_firestore/permission-denied] The caller does not have permission to execute the specified
operation.

The relevant error-causing widget was:
  UnderRepairDialog
  UnderRepairDialog:file:///Users/ken-fukushima/flutter_projects/limited_characters_diary/lib/home_page.dart:118:17

When the exception was thrown, this was the stack:
#1      AsyncError.value (package:riverpod/src/common.dart:494:7)
#2      UnderRepairDialog.build (package:limited_characters_diary/feature/update_info/under_repair_dialog.dart:16:20)
#3      _ConsumerState.build (package:flutter_riverpod/src/consumer.dart:476:19)
#4      StatefulElement.build (package:flutter/src/widgets/framework.dart:5583:27)
#5      ConsumerStatefulElement.build (package:flutter_riverpod/src/consumer.dart:539:20)
#6      HookElement.build (package:flutter_hooks/src/framework.dart:416:27)
#7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5471:15)
#8      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634:11)
#9      Element.rebuild (package:flutter/src/widgets/framework.dart:5187:7)
#10     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2895:19)
#11     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:984:21)
#12     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:457:5)
#13     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1325:15)
#14     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1255:9)
#15     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1113:5)
#16     _invoke (dart:ui/hooks.dart:312:13)
#17     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:383:5)
#18     _drawFrame (dart:ui/hooks.dart:283:31)
#19     EventChannelExtension.receiveGuardedBroadcastStream (package:_flutterfire_internals/src/exception.dart:67:43)
#20     MethodChannelDocumentReference.snapshots.<anonymous closure>
(package:cloud_firestore_platform_interface/src/method_channel/method_channel_document_reference.dart:132:18)

════════════════════════════════════════════════════════════════════════════════════════════════════
```

prod 環境では、AppCheck が動作しているので、セキュリティエラーになるのは想定通りだが、
`UnderRepairDialog` での firestore の値取得に失敗した時のハンドリングが適切に設定されていないのが原因と思われる。

release ビルドだと以下のような画面になる
<img src="![スクリーンショット 2024-05-12 7 31 00](https://github.com/haterain0203/limited_characters_diary/assets/58384546/ceaf549a-451b-4a95-b54b-d6d38510ba42)
" width=300 />

が、debug ビルドだと以下のエラー画面になっていた。
<img src="![Screenshot_20240512_073217_com futtaro limited_characters_diary](https://github.com/haterain0203/limited_characters_diary/assets/58384546/0803876f-b398-4138-81fb-f650f88eaa38)" width=300 />
